[features]
hooks = true

[mcp_servers.svelte]
command = "npx"
args = ["-y", "@sveltejs/mcp"]
enabled = false
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
enabled = false
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp"]
enabled = false
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.openapi]
command = "npx"
args = ["-y", "@ivotoby/openapi-mcp-server"]
enabled = false
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.openapi.env]
API_BASE_URL = "http://localhost:5000"
OPENAPI_SPEC_PATH = "http://localhost:5000/openapi/v1.json"
TOOLS_MODE = "dynamic"
VERBOSE = "false"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
enabled = false
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"
