<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <TargetFrameworks>$(Fx)</TargetFrameworks>
    <RootNamespace>NeoBeard</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  
  <ItemGroup>
    <Compile Include="$(CmnDir)/ffi/win32/Libs.cs" Link="FFI/Win32/Libs.cs" />
    <Compile Include="$(CmnDir)/ffi/win32/kernel32/GetConsoleMode.cs" Link="FFI/Win32/Kernel32/GetConsoleMode.cs" />
    <Compile Include="$(CmnDir)/ffi/win32/kernel32/GetStdHandle.cs" Link="FFI/Win32/Kernel32/GetStdHandle.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Colors.Primitives/src/*.csproj" />
  </ItemGroup>

</Project>
