packages:
  - lib/js/*
  - apps/apphost
  - apps/ui

allowBuilds:
  '@hugeicons/svelte': false
  esbuild: true
catalog:
  vite: 8.0.16
  vitest: 4.1.8
  vite-plus: 0.1.24
  "@vitest/browser-playwright": 4.1.8
  oxfmt: 0.53.0
