<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(Fx)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Model\NeoShip.Data.Model.csproj" />
    <ProjectReference Include="..\Data.Runtime\NeoShip.Data.Runtime.csproj" />
    <ProjectReference Include="..\ServiceDefaults\NeoShip.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
