<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <TargetFrameworks>$(Fx)</TargetFrameworks>
    <RootNamespace>NeoBeard.Secrets</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>OS Secret KeyTar Credential Store Windows Linux Darwin MacOs</PackageTags>
    <Description>
       Provides the ability to work with operating system credential stores
that store secrets/passwords similar to keytar.
    </Description>
    <PackageReleaseNotes Condition="Exists('$(MSBuildProjectDirectory)/CHANGELOG.md')">
      $([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/CHANGELOG.md"))
    </PackageReleaseNotes>
    <PackageLicenseFile Condition="Exists('$(LicensePath)')">LICENSE.md</PackageLicenseFile>
    <PackageIcon>hyprx_logo_256.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Condition="Exists('README.md')" Include="README.md" Pack="true" PackagePath=""/>
    <None Condition="Exists('$(LicensePath)')" Include="$(LicensePath)" Pack="true" PackagePath=""/>
    <None Condition="Exists('$(IconPath)')" Include="$(IconPath)" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
      <AssemblyAttribute Include="System.CLSCompliant">
          <_Parameter1>true</_Parameter1>
          <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>
</Project>