<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(Fx)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Model\NeoShip.Data.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
