<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(Fx)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>shipctl</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiSvc\NeoShip.ApiSvc.csproj" />
    <ProjectReference Include="..\Data.Model.Sqlite\NeoShip.Data.Sqlite.csproj" />
  </ItemGroup>

</Project>
