// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoShip.Data.Model;

#nullable disable

namespace NeoShip.Data.Sqlite.Migrations
{
    [DbContext(typeof(ShipDb))]
    [Migration("20260609203558_AddPasskeyMetadata")]
    partial class AddPasskeyMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GroupRole", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("TEXT")
                        .HasColumnName("groups_id");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_id");

                    b.HasKey("GroupsId", "RolesId")
                        .HasName("pk_group_role");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_group_role_roles_id");

                    b.ToTable("group_role", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.AuditEvent", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<uint?>("Asn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asn");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<string>("DataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_json");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(46)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("IpDigest")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_digest");

                    b.Property<string>("MachineName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<string>("ParentSpanId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_span_id");

                    b.Property<string>("Region")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("RiskFlagsJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_flags_json");

                    b.Property<ushort>("RiskLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_level");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SpanId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("span_id");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_events_timestamp");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_audit_events_type");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EmailUpcase")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_upcase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameUpcase")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_upcase");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_groups_org_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameUpcase")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_upcase");

                    b.Property<ushort>("OrganizationPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_plan_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<ushort>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<ushort>("TenantModeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_mode_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orgs");

                    b.ToTable("orgs", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameUpcase")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_upcase");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_roles_created_by");

                    b.HasIndex("OrgId", "NameUpcase")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_org_id_name_upcase");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.RoleClaim", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_role_claims_created_by");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameUpcase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_upcase");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_accounts");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_service_accounts_created_by");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_service_accounts_org_id");

                    b.ToTable("service_accounts", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_digest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes_json");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_account_api_keys");

                    b.HasIndex("KeyDigest")
                        .HasDatabaseName("ix_service_account_api_keys_key_digest");

                    b.HasIndex("ServiceAccountId")
                        .HasDatabaseName("ix_service_account_api_keys_service_account_id");

                    b.ToTable("service_account_api_keys", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountApiKeyClaim", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceAccountApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_api_key_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_account_api_key_claims");

                    b.HasIndex("ServiceAccountApiKeyId")
                        .HasDatabaseName("ix_service_account_api_key_claims_service_account_api_key_id");

                    b.ToTable("service_account_api_key_claims", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_account_claims");

                    b.HasIndex("ServiceAccountId")
                        .HasDatabaseName("ix_service_account_claims_service_account_id");

                    b.ToTable("service_account_claims", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EmailUpcase")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_upcase");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(39)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_ip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameUpcase")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_upcase");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<ushort>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EmailUpcase")
                        .HasDatabaseName("ix_users_email_upcase");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_users_org_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_digest");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes_json");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_api_keys");

                    b.HasIndex("KeyDigest")
                        .HasDatabaseName("ix_user_api_keys_key_digest");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_api_keys_user_id");

                    b.ToTable("user_api_keys", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserApiKeyClaim", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_api_key_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_api_key_claims");

                    b.HasIndex("UserApiKeyId")
                        .HasDatabaseName("ix_user_api_key_claims_user_api_key_id");

                    b.ToTable("user_api_key_claims", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserClaim", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EmailDigest")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_digest");

                    b.Property<string>("EmailUpcase")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_upcase");

                    b.Property<DateTime?>("ErasedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("erased_at");

                    b.Property<ushort>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationTokenDigest")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("verification_token_digest");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("verification_token_expires_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_user_emails");

                    b.HasIndex("EmailDigest")
                        .HasDatabaseName("ix_user_emails_email_digest");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_emails_user_id");

                    b.HasIndex("VerificationTokenDigest")
                        .HasDatabaseName("ix_user_emails_verification_token_digest");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserIdentityProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<byte[]>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("client_secret_enc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IssuerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("issuer_url");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<ushort>("ProviderTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_type_id");

                    b.Property<ushort>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_identity_providers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_identity_providers_user_id");

                    b.HasIndex("ProviderTypeId", "OrgId")
                        .HasDatabaseName("ix_user_identity_providers_provider_type_id_org_id");

                    b.HasIndex("ProviderTypeId", "UserId")
                        .HasDatabaseName("ix_user_identity_providers_provider_type_id_user_id");

                    b.ToTable("user_identity_providers", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserKnownNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<uint?>("Asn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asn");

                    b.Property<uint>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(46)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("IpDigest")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_digest");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_known_networks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_known_networks_user_id");

                    b.ToTable("user_known_networks", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserMfaFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TransportsJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("transports_json");

                    b.Property<ushort>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("ValueEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("value_enc");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_at");

                    b.Property<byte[]>("WebAuthnCredentialId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("web_authn_credential_id");

                    b.Property<string>("WebAuthnCredentialIdDigest")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_authn_credential_id_digest");

                    b.Property<byte[]>("WebAuthnPublicKeyCredentialData")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("web_authn_public_key_credential_data");

                    b.Property<uint>("WebAuthnSignCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("web_authn_sign_count");

                    b.HasKey("Id")
                        .HasName("pk_user_mfa_factors");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_mfa_factors_user_id");

                    b.HasIndex("WebAuthnCredentialIdDigest")
                        .HasDatabaseName("ix_user_mfa_factors_web_authn_credential_id_digest");

                    b.ToTable("user_mfa_factors", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserPasswordAuth", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_algorithm");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iterations");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_salt");

                    b.Property<string>("ResetTokenDigest")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_token_digest");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_token_expires_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_password_auths");

                    b.HasIndex("ResetTokenDigest")
                        .HasDatabaseName("ix_user_password_auths_reset_token_digest");

                    b.ToTable("user_password_auths", (string)null);
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClaimsJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("claims_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(46)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("IpDigest")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_digest");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("MfaVerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("mfa_verified_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RiskFlagsJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_flags_json");

                    b.Property<ushort>("RiskLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_level");

                    b.Property<string>("TokenDigest")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_digest");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_user_sessions_org_id");

                    b.HasIndex("TokenDigest")
                        .HasDatabaseName("ix_user_sessions_token_digest");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("TEXT")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("group_members", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("TEXT")
                        .HasColumnName("members_id");

                    b.HasKey("GroupId", "MembersId")
                        .HasName("pk_group_members");

                    b.HasIndex("MembersId")
                        .HasDatabaseName("ix_group_members_members_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("group_owners", b =>
                {
                    b.Property<Guid>("Group1Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("group1id");

                    b.Property<Guid>("OwnersId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owners_id");

                    b.HasKey("Group1Id", "OwnersId")
                        .HasName("pk_group_owners");

                    b.HasIndex("OwnersId")
                        .HasDatabaseName("ix_group_owners_owners_id");

                    b.ToTable("group_owners", (string)null);
                });

            modelBuilder.Entity("group_service_account_members", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<Guid>("ServiceAccountMembersId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_members_id");

                    b.HasKey("GroupId", "ServiceAccountMembersId")
                        .HasName("pk_group_service_account_members");

                    b.HasIndex("ServiceAccountMembersId")
                        .HasDatabaseName("ix_group_service_account_members_service_account_members_id");

                    b.ToTable("group_service_account_members", (string)null);
                });

            modelBuilder.Entity("group_service_account_owners", b =>
                {
                    b.Property<Guid>("Group1Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("group1id");

                    b.Property<Guid>("ServiceAccountOwnersId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_owners_id");

                    b.HasKey("Group1Id", "ServiceAccountOwnersId")
                        .HasName("pk_group_service_account_owners");

                    b.HasIndex("ServiceAccountOwnersId")
                        .HasDatabaseName("ix_group_service_account_owners_service_account_owners_id");

                    b.ToTable("group_service_account_owners", (string)null);
                });

            modelBuilder.Entity("service_account_api_key_roles", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("ServiceAccountApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_account_api_key_id");

                    b.HasKey("RolesId", "ServiceAccountApiKeyId")
                        .HasName("pk_service_account_api_key_roles");

                    b.HasIndex("ServiceAccountApiKeyId")
                        .HasDatabaseName("ix_service_account_api_key_roles_service_account_api_key_id");

                    b.ToTable("service_account_api_key_roles", (string)null);
                });

            modelBuilder.Entity("GroupRole", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_role_groups_groups_id");

                    b.HasOne("NeoShip.Data.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_role_roles_roles_id");
                });

            modelBuilder.Entity("NeoShip.Data.Model.Group", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_orgs_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("NeoShip.Data.Model.Role", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_users_created_by");

                    b.HasOne("NeoShip.Data.Model.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_orgs_org_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("NeoShip.Data.Model.RoleClaim", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_users_created_by");

                    b.HasOne("NeoShip.Data.Model.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccount", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_users_created_by");

                    b.HasOne("NeoShip.Data.Model.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_orgs_org_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountApiKey", b =>
                {
                    b.HasOne("NeoShip.Data.Model.ServiceAccount", "ServiceAccount")
                        .WithMany()
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_api_keys_service_accounts_service_account_id");

                    b.Navigation("ServiceAccount");
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountApiKeyClaim", b =>
                {
                    b.HasOne("NeoShip.Data.Model.ServiceAccountApiKey", "ServiceAccountApiKey")
                        .WithMany()
                        .HasForeignKey("ServiceAccountApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_api_key_claims_service_account_api_keys_service_account_api_key_id");

                    b.Navigation("ServiceAccountApiKey");
                });

            modelBuilder.Entity("NeoShip.Data.Model.ServiceAccountClaim", b =>
                {
                    b.HasOne("NeoShip.Data.Model.ServiceAccount", "ServiceAccount")
                        .WithMany()
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_claims_service_accounts_service_account_id");

                    b.Navigation("ServiceAccount");
                });

            modelBuilder.Entity("NeoShip.Data.Model.User", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_orgs_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserApiKey", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_api_keys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserApiKeyClaim", b =>
                {
                    b.HasOne("NeoShip.Data.Model.UserApiKey", "UserApiKey")
                        .WithMany()
                        .HasForeignKey("UserApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_api_key_claims_user_api_keys_user_api_key_id");

                    b.Navigation("UserApiKey");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserEmail", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_emails_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserIdentityProvider", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_identity_providers_users_user_id");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserKnownNetwork", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_known_networks_users_user_id");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserMfaFactor", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mfa_factors_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserPasswordAuth", b =>
                {
                    b.HasOne("NeoShip.Data.Model.User", "User")
                        .WithOne()
                        .HasForeignKey("NeoShip.Data.Model.UserPasswordAuth", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_password_auths_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoShip.Data.Model.UserSession", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_orgs_org_id");

                    b.HasOne("NeoShip.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_roles_roles_id");

                    b.HasOne("NeoShip.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("group_members", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("NeoShip.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_members_id");
                });

            modelBuilder.Entity("group_owners", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("Group1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_owners_groups_group1id");

                    b.HasOne("NeoShip.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_owners_users_owners_id");
                });

            modelBuilder.Entity("group_service_account_members", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_account_members_groups_group_id");

                    b.HasOne("NeoShip.Data.Model.ServiceAccount", null)
                        .WithMany()
                        .HasForeignKey("ServiceAccountMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_account_members_service_accounts_service_account_members_id");
                });

            modelBuilder.Entity("group_service_account_owners", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("Group1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_account_owners_groups_group1id");

                    b.HasOne("NeoShip.Data.Model.ServiceAccount", null)
                        .WithMany()
                        .HasForeignKey("ServiceAccountOwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_account_owners_service_accounts_service_account_owners_id");
                });

            modelBuilder.Entity("service_account_api_key_roles", b =>
                {
                    b.HasOne("NeoShip.Data.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_api_key_roles_roles_roles_id");

                    b.HasOne("NeoShip.Data.Model.ServiceAccountApiKey", null)
                        .WithMany()
                        .HasForeignKey("ServiceAccountApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_api_key_roles_service_account_api_keys_service_account_api_key_id");
                });

            modelBuilder.Entity("NeoShip.Data.Model.Role", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
